#!/usr/bin/env python3
"""Generate sim/src/room_menu_gen.rs from rmMenu's instance list (game.unx).

Computes wall autotile frames offline (obj_wall_n Step_2 semantics, area 0):
  4-bit orthogonal neighbor mask (up1/right2/down4/left8),
  remap {0,2,8,10,14}->14, else if not in {6,12} -> 15,
  raw 15: corner light overlays (frames UL25/UR24/DL21/DR20) for absent
  diagonal walls; all 4 diagonals present -> 'surrounded': replaced by a
  tileCavern filler tile at (x-8, y-8) and the instance destroyed.
Also emits grass tuft positions and the RNG-consumer creation order.
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gmdata

DST = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
inst = gmdata.room_instances(20)

walls = [(x, y) for x, y, n in inst if n == 'objWall_n']
wallset = set(walls)
grass = [(x, y) for x, y, n in inst if n == 'objGrass']

wall_draws = []   # (x, y, frame)
light_draws = []  # (x, y, frame) drawn right after the base per wall
fillers = []      # (x-8, y-8)
for (x, y) in walls:
    i = 0
    if (x, y - 16) in wallset: i += 1
    if (x + 16, y) in wallset: i += 2
    if (x, y + 16) in wallset: i += 4
    if (x - 16, y) in wallset: i += 8
    raw = i
    lights = []
    surrounded = False
    if raw == 15:
        ul = (x - 16, y - 16) not in wallset
        ur = (x + 16, y - 16) not in wallset
        dl = (x - 16, y + 16) not in wallset
        dr = (x + 16, y + 16) not in wallset
        if not (ul or ur or dl or dr):
            surrounded = True
        else:
            if ul: lights.append(25)
            if ur: lights.append(24)
            if dl: lights.append(21)
            if dr: lights.append(20)
    if surrounded:
        fillers.append((x - 8, y - 8))
        continue
    if i in (0, 2, 8, 10, 14):
        i = 14
    elif i not in (6, 12):
        i = 15
    wall_draws.append((x, y, i, lights if raw == 15 else []))

L = ['// GENERATED by tools/gen_room.py — do not edit.',
     '// rmMenu walls: (x, y, base frame, light overlay frames [UL25 UR24 DL21 DR20])',
     f'pub const MENU_WALLS: [(i32, i32, u16, [i16; 4]); {len(wall_draws)}] = [']
for x, y, f, lights in wall_draws:
    l4 = (lights + [-1, -1, -1, -1])[:4]
    L.append(f'    ({x}, {y}, {f}, [{l4[0]}, {l4[1]}, {l4[2]}, {l4[3]}]),')
L += ['];', '',
      f'// surrounded walls became tileCavern filler tiles at these top-lefts',
      f'pub const MENU_FILLERS: [(i32, i32); {len(fillers)}] = [']
for x, y in fillers:
    L.append(f'    ({x}, {y}),')
L += ['];', '',
      '// grass tufts in creation order (RNG consumption order)',
      f'pub const MENU_GRASS: [(i32, i32); {len(grass)}] = [']
for x, y in grass:
    L.append(f'    ({x}, {y}),')
L += ['];']
open(f'{DST}/sim/src/room_menu_gen.rs', 'w').write('\n'.join(L) + '\n')

print('walls drawn:', len(wall_draws), 'fillers:', len(fillers), 'grass:', len(grass))
print('rng consumer order:')
for x, y, n in inst:
    if n in ('objPlayer_n', 'objGrass', 'objTree', 'groundTrees'):
        print('  ', n, x, y)

# ---- collision rect tables (player physics) --------------------------------
# parentWall = objWall_n + objInvisWall; parentThinwall = groundBench;
# sParentSolid = union. Rects in room coords, inclusive bounds.
inst2 = gmdata.room_instances(20)
# re-read with scales
def room_instances_scaled(idx):
    off, _ = gmdata.CH['ROOM']
    r = gmdata.R(gmdata.buf, off)
    p = r.ptrlist()[idx]
    rr = gmdata.R(gmdata.buf, p)
    for _ in range(12):
        rr.u32()
    objs = rr.u32()
    ir = gmdata.R(gmdata.buf, objs)
    objnames = gmdata.asset_names('OBJT')
    out = []
    for ip in ir.ptrlist():
        i = gmdata.R(gmdata.buf, ip)
        x = i.i32(); y = i.i32(); oid = i.i32(); i.i32(); i.i32()
        sx = i.f32(); sy = i.f32()
        out.append((x, y, objnames[oid], sx, sy))
    return out

wall_rects = []
for (x, y, n, sx, sy) in room_instances_scaled(20):
    if n == 'objWall_n':
        if (x, y) in {(w[0], w[1]) for w in walls}:
            # all walls collide (surrounded ones destroyed at end-step frame 2,
            # but they are interior; the player can never reach them, and the
            # filler tile has no instance -> exclude destroyed ones)
            pass
    if n == 'objWall_n' and not any(f == (x - 8, y - 8) for f in fillers):
        wall_rects.append((x - 8, y - 8, x + 7, y + 7))
    elif n == 'objInvisWall':
        l = x - 8 * sx; r = x + 8 * sx - 1
        t = y - 8 * sy; b = y + 8 * sy - 1
        wall_rects.append((int(l), int(t), int(r), int(b)))
# objWell (272,512) spawns 4 invis walls in its Create
for wx in (272, 288, 368, 384):
    wall_rects.append((wx - 8, 512 - 8, wx + 7, 512 + 7))
thin_rects = [(101, 514, 124, 515)]  # groundBench seat (5..28 x 18..19 rel)

L2 = ['', '// collision rects (room coords, inclusive): parentWall family',
      f'pub const MENU_WALL_RECTS: [(i32, i32, i32, i32); {len(wall_rects)}] = [']
for r_ in wall_rects:
    L2.append(f'    {r_},')
L2 += ['];', '',
       '// parentThinwall family (platforms: collide only from above)',
       f'pub const MENU_THIN_RECTS: [(i32, i32, i32, i32); {len(thin_rects)}] = [']
for r_ in thin_rects:
    L2.append(f'    {r_},')
L2 += ['];']
open(f'{DST}/sim/src/room_menu_gen.rs', 'a').write('\n'.join(L2) + '\n')
print('collision rects:', len(wall_rects), 'walls,', len(thin_rects), 'thin')

# ---- rmMain (room 11) static instances -> room_main_gen.rs ----------------
main_inst = room_instances_scaled(11)
from collections import Counter
by_obj = Counter(n for _, _, n, _, _ in main_inst)
L3 = ['// GENERATED by tools/gen_room.py — rmMain static instances (creation order)',
      '// (x, y, object-kind): 0=objWall_n 1=objBuilder 2=objDitherAbove 3=other',
      f'pub const MAIN_INSTANCES: [(i32, i32, u8); {len(main_inst)}] = [']
KIND = {'objWall_n': 0, 'objBuilder': 1, 'objDitherAbove': 2}
for (x, y, n, sx, sy) in main_inst:
    L3.append(f'    ({x}, {y}, {KIND.get(n, 3)}), // {n}')
L3 += ['];']
open(f'{DST}/sim/src/room_main_gen.rs', 'w').write('\n'.join(L3) + '\n')
print('rmMain instances:', dict(by_obj))
