#!/usr/bin/env python3
"""Extract area-1 level-pattern tables from the decompiled GML into Rust.

Sources (decompiled_downwell/code/global_script/):
  scrStartPat1.gml -> partStart   scrEndPat1.gml  -> partEnd
  scrRightPat1.gml -> partRight   scrShopPat1.gml -> partShopR
  scrLevelPat1.gml -> partMain
Each table is a sequence of `partX[i] = "chunk";` assignments with
`partX[100] = i` storing the max index (irandom(part[100]) picks uniformly).

Output: sim/src/patterns_gen.rs — &str arrays, chunk text verbatim
(the builder strips \\t and leading CR/LF at stamp time, GM-identically).
"""
import os, re, sys

SRC = os.path.expanduser('~/sources/downwell/decompiled_downwell/code/global_script')
DST = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FILES = [
    ('PART_START', 'scrStartPat1.gml', 'partStart'),
    ('PART_END', 'scrEndPat1.gml', 'partEnd'),
    ('PART_RIGHT', 'scrRightPat1.gml', 'partRight'),
    ('PART_SHOP_R', 'scrShopPat1.gml', 'partShopR'),
    ('PART_MAIN', 'scrLevelPat1.gml', 'partMain'),
]

def unescape(s):
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == '\\' and i + 1 < len(s):
            n = s[i + 1]
            out.append({'r': '\r', 'n': '\n', 't': '\t', '\\': '\\', '"': '"'}.get(n, n))
            i += 2
        else:
            out.append(c)
            i += 1
    return ''.join(out)

def rust_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '\\r').replace('\n', '\\n').replace('\t', '\\t') + '"'

lines = ['// GENERATED by tools/gen_patterns.py from the decompiled GML — do not edit.',
         '// Area-1 chunk tables; irandom(len-1) picks (GM: irandom(part[100])).', '']
for const, fname, var in FILES:
    src = open(f'{SRC}/{fname}').read()
    chunks = [unescape(m) for m in re.findall(rf'{var}\[i\] = "((?:[^"\\]|\\.)*)"', src)]
    assert chunks, f'no chunks parsed from {fname}'
    # sanity: the [100] sentinel must equal len-1
    m = re.search(rf'{var}\[100\] = i', src)
    assert m, f'no sentinel in {fname}'
    lines.append(f'pub static {const}: [&str; {len(chunks)}] = [')
    for c in chunks:
        lines.append(f'    {rust_str(c)},')
    lines.append('];\n')
    print(f'{const}: {len(chunks)} chunks')
open(f'{DST}/sim/src/patterns_gen.rs', 'w').write('\n'.join(lines) + '\n')
print('-> sim/src/patterns_gen.rs')
