#!/usr/bin/env python3
"""Pack sprites (by GM asset id, metadata from game.unx via gmdata) plus font0
into one RGBA atlas; generate Rust tables.

Outputs:
  assets/atlas.rgba          raw RGBA8 (ATLAS_W x ATLAS_H)
  assets/atlas.png           compressed browser/GPU upload asset
  sim/src/sprites_gen.rs     (id -> origin, size, nframes) + font metrics
  app/src/atlas_gen.rs       (id, frame) -> atlas pixel rect
"""
import os, sys, csv
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gmdata

SRC = os.path.expanduser('~/sources/downwell/decompiled_downwell')
DST = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ATLAS_W, ATLAS_H = 1024, 1024

# GM sprite asset ids to pack (decompiled PNGs are untrimmed full frames)
WANT = [
    76, 739,  # sprTileSurface (wall autotile), tileCavern (filler source)
    20, 27, 37, 1, 3, 10,  # player: wall, run, air, spin, shoot, yay
    94, 95, 457, 459, 603, 111, 101,  # fx: jumpSmall, jump, casing, bullet, muzzle, recharge, bulletHitWall
    654, 655, 656,  # DOWNWELL title fade + sparkles
    696, 695, 733, 408,                       # splash: devolver, controls, dither, border
    373, 376, 378, 383, 413, 414, 415, 416,   # HUD
    418, 419, 421, 422, 590,
    11, 12, 13, 14, 15, 31,                   # player nap poses + idle
    369, 596, 631, 635, 636, 637, 638,        # scene: nightsky, camlock, tree, grass
    640, 642, 646, 729,                       # bench, well, trees, infosp
]

table = {s['idx']: s for s in gmdata.sprites_table()}
atlas = Image.new('RGBA', (ATLAS_W, ATLAS_H), (0, 0, 0, 0))

# simple shelf packer
shelf_x, shelf_y, shelf_h = 0, 0, 0
def alloc(w, h):
    global shelf_x, shelf_y, shelf_h
    if shelf_x + w > ATLAS_W:
        shelf_y += shelf_h
        shelf_x, shelf_h = 0, 0
    assert shelf_y + h <= ATLAS_H, 'atlas full'
    pos = (shelf_x, shelf_y)
    shelf_x += w
    shelf_h = max(shelf_h, h)
    return pos

rects = {}  # (id, frame) -> (x, y, w, h)
jobs = []
for sid in WANT:
    s = table[sid]
    for f in range(s['nframes']):
        jobs.append((s['h'], sid, f, s))
jobs.sort(key=lambda j: -j[0])  # tallest first for shelf efficiency
for _, sid, f, s in jobs:
    p = f'{SRC}/sprites/{s["name"]}/{s["name"]}_{f}.png'
    im = Image.open(p).convert('RGBA')
    assert im.size == (s['w'], s['h']), (p, im.size, s)
    x, y = alloc(s['w'], s['h'])
    atlas.paste(im, (x, y))
    rects[(sid, f)] = (x, y, s['w'], s['h'])

# font page + white fill patch
fx, fy = alloc(256, 256)
atlas.paste(Image.open(f'{SRC}/fonts/font0.png').convert('RGBA'), (fx, fy))
wx, wy = alloc(8, 8)
atlas.paste(Image.new('RGBA', (8, 8), (255, 255, 255, 255)), (wx, wy))

os.makedirs(f'{DST}/assets', exist_ok=True)
open(f'{DST}/assets/atlas.rgba', 'wb').write(atlas.tobytes())
atlas.save(f'{DST}/assets/atlas.png', optimize=True, compress_level=9)

# ---- font0 glyphs ----
glyphs = {}
for r in list(csv.reader(open(f'{SRC}/fonts/glyphs_font0.csv'), delimiter=';'))[1:]:
    if r and r[0].isdigit():
        ch, x, y, w, h, shift, off = (int(v) for v in r[:7])
        glyphs[ch] = (x, y, w, h, shift, off)

# ---- sim tables ----
L = ['// GENERATED by tools/pack_assets.py — do not edit.',
     '// (origin_x, origin_y, frames) per GM sprite asset id',
     'pub fn sprite_meta(id: u16) -> (i32, i32, u16) {',
     '    match id {']
for sid in sorted(WANT):
    s = table[sid]
    L.append(f'        {sid} => ({s["ox"]}, {s["oy"]}, {s["nframes"]}), // {s["name"]} {s["w"]}x{s["h"]}')
L += ['        _ => (0, 0, 1),', '    }', '}', '',
      'pub const FONT0_FIRST: u16 = 32;',
      'pub const FONT0_LINE_H: i32 = 10;',
      '// (shift, offset, width) per ASCII 32..127',
      'pub const FONT0_METRICS: [(i8, i8, i8); 96] = [']
for ch in range(32, 128):
    x, y, w, h, shift, off = glyphs.get(ch, (0, 0, 0, 0, 8, 0))
    L.append(f'    ({shift}, {off}, {w}), // {ch} {chr(ch)!r}')
L.append('];')
open(f'{DST}/sim/src/sprites_gen.rs', 'w').write('\n'.join(L) + '\n')

# ---- app rect table ----
A = ['// GENERATED by tools/pack_assets.py — do not edit.',
     f'pub const ATLAS_W: u32 = {ATLAS_W};',
     f'pub const ATLAS_H: u32 = {ATLAS_H};',
     'pub fn sprite_rect(sprite: u16, frame: u16) -> (u32, u32, u32, u32) {',
     '    match (sprite, frame) {',
     f'        (998, _) => ({wx+2}, {wy+2}, 4, 4), // solid white fill',
     f'        (997, _) => ({rects[(739,0)][0]+48}, {rects[(739,0)][1]+48}, 16, 16), // tileCavern filler subrect (48,48,16,16)']
for (sid, f), (x, y, w, h) in sorted(rects.items()):
    A.append(f'        ({sid}, {f}) => ({x}, {y}, {w}, {h}),')
A += ['        (999, c) => { // font0 glyph, frame = ascii']
A.append('            match c {')
for ch in range(32, 128):
    if ch in glyphs:
        x, y, w, h, _, _ = glyphs[ch]
        A.append(f'                {ch} => ({fx+x}, {fy+y}, {w}, {h}),')
A += ['                _ => (0, 0, 0, 0),', '            }', '        }',
      '        (s, f) if f > 0 => sprite_rect(s, 0), // clamp missing frames to 0',
      '        _ => (0, 0, 0, 0),',
      '    }', '}']
open(f'{DST}/app/src/atlas_gen.rs', 'w').write('\n'.join(A) + '\n')
print(f'packed {len(rects)} frames, atlas ends at y={shelf_y + shelf_h}')
