// downwell_rs web: browser frontend. Same sim, same atlas, same shader
// semantics as app/, but software-rasterized into an RGBA framebuffer that
// the JS glue (www/index.html) blits to a canvas.
//
// Two views, chosen at boot():
//  - cinema (default): 320x180 GUI units, 16:9 "movie" crop of the world.
//    No HUD, no tablet borders, no 160-wide surface clip. Works without
//    touching sim: sim emits every world draw view-relative (no culling) and
//    relies on the shader clip for windowing, so this frontend just skips the
//    chrome (pal != 2), re-centers the camera for the wider window, and
//    rasterizes with a wider clip. The sim's own view math is untouched —
//    frame-accuracy work in app/ is unaffected.
//  - classic: the full 760x568 GM window (HUD, borders, 160x284 surface).
//
// Splash skip: boot() zeroes show_splash, the sim's own "no splash" path.
//
// atlas_gen.rs is generated by tools/pack_assets.py into app/src; reference
// it in place (never copy) so a regenerated atlas reaches both frontends.
#[path = "../../app/src/atlas_gen.rs"]
mod atlas_gen;

// classic view: GUI units -> window px, same mapping as app/src/main.rs
const CLASSIC_W: usize = 760;
const CLASSIC_H: usize = 568;
const SCALE: f32 = 2.0;
const CLASSIC_OFF_X: f32 = 220.0;

// cinema view, GUI units: the full 416-wide room (the frame locks — no
// horizontal panning), exactly the surface height — so vertically it frames
// what classic frames
const CIN_W: i32 = 416;
const CIN_H: i32 = 284;

// framebuffer holds whichever mode is larger
const FB_LEN: usize = {
    let cin = (CIN_W as usize * 2) * (CIN_H as usize * 2);
    let classic = CLASSIC_W * CLASSIC_H;
    (if cin > classic { cin } else { classic }) * 4
};

static ATLAS: &[u8] = include_bytes!("../../assets/atlas.rgba");

// rasterization params for one view mode
struct View {
    w: usize,          // fb px
    h: usize,
    off_x: f32,        // window-px x offset after scale
    dx: f32,           // GUI-unit world shift (cinema re-centering)
    dy: f32,
    clip: (f32, f32),  // pal=2 x clip, window px
}

struct Web {
    gs: sim::GameState,
    dl: sim::DrawList,
    fb: [u8; FB_LEN],
    classic: bool,
}

// const-initialized: lives in zeroed wasm memory, no startup construction on
// the (small) wasm shadow stack.
static mut WEB: Web = Web {
    gs: sim::GameState::new(),
    dl: sim::DrawList::EMPTY,
    fb: [0; FB_LEN],
    classic: false,
};

fn web() -> &'static mut Web {
    // single-threaded wasm; JS calls are serialized
    unsafe { &mut *core::ptr::addr_of_mut!(WEB) }
}

#[no_mangle]
pub extern "C" fn boot(classic: u32) {
    let w = web();
    w.gs = sim::GameState::new();
    w.gs.boot(0); // frozen-clock default seed (matches geist elapsed=0)
    w.gs.show_splash = 0; // skip the intro credits (sim's own no-splash path)
    w.classic = classic != 0;
}

// input bits: 1 = space, 2 = left, 4 = right
#[no_mangle]
pub extern "C" fn frame(input: u32) {
    let w = web();
    let inp = sim::Input {
        space: input & 1 != 0,
        left: input & 2 != 0,
        right: input & 4 != 0,
    };
    sim::tick(&mut w.gs, inp);
    sim::draw(&mut w.gs, &mut w.dl); // mutates state like GM's draw event: once per tick
    if w.classic {
        rasterize_classic(&w.dl, &mut w.fb);
    } else {
        rasterize_cinema(&w.gs, &w.dl, &mut w.fb);
    }
}

#[no_mangle]
pub extern "C" fn fb_ptr() -> *const u8 {
    web().fb.as_ptr()
}

#[no_mangle]
pub extern "C" fn fb_w() -> u32 {
    if web().classic { CLASSIC_W as u32 } else { (CIN_W as f32 * SCALE) as u32 }
}

#[no_mangle]
pub extern "C" fn fb_h() -> u32 {
    if web().classic { CLASSIC_H as u32 } else { (CIN_H as f32 * SCALE) as u32 }
}

// ---- view assembly ---------------------------------------------------------

fn clear(fb: &mut [u8], n: usize) {
    fb[..n * 4].chunks_exact_mut(4).for_each(|p| p.copy_from_slice(&[0, 0, 0, 255]));
}

fn rasterize_classic(dl: &sim::DrawList, fb: &mut [u8]) {
    let v = View {
        w: CLASSIC_W,
        h: CLASSIC_H,
        off_x: CLASSIC_OFF_X,
        dx: 0.0,
        dy: 0.0,
        clip: (220.0, 540.0),
    };
    clear(fb, v.w * v.h);
    for c in &dl.cmds[..dl.n] {
        draw_cmd(c, fb, &v);
    }
}

// Movie crop: world draws only (pal=2), camera re-centered for the wider
// window. sim's draws are relative to its 160x284 view origin (vx, vy);
// shifting them by (vx - vx_cin, vy - vy_cin) re-anchors them to ours.
fn rasterize_cinema(gs: &sim::GameState, dl: &sim::DrawList, fb: &mut [u8]) {
    // sim's view origin (sim/src/lib.rs app_surface), recomputed identically
    let vx = (gs.cam.x - 80).clamp(0, 416 - 160);
    let vy = (gs.cam.y - 142).clamp(0, 1200 - 284);
    // ours: camera-centered, clamped to the same room bounds
    let vxc = (gs.cam.x - CIN_W / 2).clamp(0, 416 - CIN_W);
    let vyc = (gs.cam.y - CIN_H / 2).clamp(0, 1200 - CIN_H);
    let v = View {
        w: (CIN_W as f32 * SCALE) as usize,
        h: (CIN_H as f32 * SCALE) as usize,
        off_x: 0.0,
        dx: (vx - vxc) as f32,
        dy: (vy - vyc) as f32,
        clip: (0.0, CIN_W as f32 * SCALE),
    };
    clear(fb, v.w * v.h);
    // the rmMenu dissolve tiles the 160x284 surface; retile it over the whole
    // movie window at the same dither frame (view-anchored, not world)
    let mut dissolve: Option<u16> = None;
    for c in &dl.cmds[..dl.n] {
        if c.pal != 2 {
            continue; // HUD, tablet borders, splash overlay
        }
        if c.sprite == sim::spr::DITHER {
            dissolve = Some(c.frame);
            continue;
        }
        // bgNightsky: GM parallaxes it by re-anchoring it to the view every
        // frame (sim recomputes sky_x/sky_y from the stale view), which drags
        // the stars along with the camera. In the movie frame the backdrop is
        // world-locked at its camera-at-rest position — (146,407), the sim's
        // boot values; 119/104 is the draw origin from menu.rs — so it can't
        // slide against the rest of the scene. (+10,+86): framing nudge for
        // the movie crop.
        if c.sprite == 369 {
            let mut fixed = *c;
            fixed.x = (146 + 10 - 119 - vx) as f32;
            fixed.y = (407 + 86 - 104 - vy) as f32;
            draw_cmd(&fixed, fb, &v);
            continue;
        }
        // no DOWNWELL wordmark in the movie frame: skip the title fade
        // (654) and its sparkles (655/656). The sim still runs the whole
        // title state machine — its RNG consumption is part of the
        // frame-accuracy contract — we just don't draw it.
        if matches!(c.sprite, 654..=656) {
            continue;
        }
        // the surface clear rect (already covered by our own clear)
        if c.sprite == sim::spr::RECT
            && c.color == sim::C_BLACK
            && c.x == 0.0
            && c.y == 0.0
            && c.w == 160.0
            && c.h == 284.0
        {
            continue;
        }
        draw_cmd(c, fb, &v);
    }
    if let Some(frame) = dissolve {
        let anchored = View { dx: 0.0, dy: 0.0, ..v };
        let mut y = 0;
        while y < CIN_H {
            let mut x = 0;
            while x < CIN_W {
                let tile = sim::DrawCmd {
                    sprite: sim::spr::DITHER,
                    frame,
                    x: x as f32,
                    y: y as f32,
                    w: 8.0,
                    h: 8.0,
                    color: sim::C_WHITE,
                    pal: 2,
                    rot: 0.0,
                };
                draw_cmd(&tile, fb, &anchored);
                x += 8;
            }
            y += 8;
        }
    }
}

// ---- software rasterizer: mirrors app/src/shader.wgsl ---------------------

fn draw_cmd(c: &sim::DrawCmd, fb: &mut [u8], v: &View) {
    let (rx, ry, rw, rh) = atlas_gen::sprite_rect(c.sprite, c.frame);
    if rw == 0 || rh == 0 {
        return;
    }
    // negative w/h flips: normalize the rect, swap uv (as main.rs does)
    let flip = c.w < 0.0;
    let (gx, gw) = if flip { (c.x + c.w, -c.w) } else { (c.x, c.w) };
    let (u0, u1) = if flip {
        ((rx + rw) as f32, rx as f32)
    } else {
        (rx as f32, (rx + rw) as f32)
    };
    let flipv = c.h < 0.0;
    let (gy, gh) = if flipv { (c.y + c.h, -c.h) } else { (c.y, c.h) };
    let (v0, v1) = if flipv {
        ((ry + rh) as f32, ry as f32)
    } else {
        (ry as f32, (ry + rh) as f32)
    };
    // window-px rect
    let wx = (gx + v.dx) * SCALE + v.off_x;
    let wy = (gy + v.dy) * SCALE;
    let ww = gw * SCALE;
    let wh = gh * SCALE;

    let tint = [
        ((c.color >> 24) & 0xFF) as f32 / 255.0,
        ((c.color >> 16) & 0xFF) as f32 / 255.0,
        ((c.color >> 8) & 0xFF) as f32 / 255.0,
        (c.color & 0xFF) as f32 / 255.0,
    ];
    let th = c.rot.to_radians();

    // pixel bounds: AABB of the (possibly rotated) quad
    let (x0, x1, y0, y1) = if th == 0.0 {
        (wx, wx + ww, wy, wy + wh)
    } else {
        let ctr = (wx + 0.5 * ww, wy + 0.5 * wh);
        let (s, co) = th.sin_cos();
        let mut xs = (f32::MAX, f32::MIN);
        let mut ys = (f32::MAX, f32::MIN);
        for corner in [(wx, wy), (wx + ww, wy), (wx, wy + wh), (wx + ww, wy + wh)] {
            let d = (corner.0 - ctr.0, corner.1 - ctr.1);
            // GM image_angle CCW, screen y down (shader vs_main)
            let px = ctr.0 + d.0 * co + d.1 * s;
            let py = ctr.1 - d.0 * s + d.1 * co;
            xs = (xs.0.min(px), xs.1.max(px));
            ys = (ys.0.min(py), ys.1.max(py));
        }
        (xs.0, xs.1, ys.0, ys.1)
    };
    // pal 2: clip to the app-surface window, like the shader
    let clip_x = if c.pal == 2 { v.clip } else { (0.0, v.w as f32) };
    let px0 = (x0.max(clip_x.0) - 0.5).ceil().max(0.0) as usize;
    let px1 = ((x1.min(clip_x.1) - 0.5).ceil()).clamp(0.0, v.w as f32) as usize;
    let py0 = (y0.max(0.0) - 0.5).ceil() as usize;
    let py1 = ((y1 - 0.5).ceil()).clamp(0.0, v.h as f32) as usize;

    let (s, co) = th.sin_cos();
    let ctr = (wx + 0.5 * ww, wy + 0.5 * wh);
    for py in py0..py1 {
        for px in px0..px1 {
            // pixel center -> quad-local t in [0,1)^2
            let (mut fx, mut fy) = (px as f32 + 0.5, py as f32 + 0.5);
            if th != 0.0 {
                // inverse of the vertex rotation
                let d = (fx - ctr.0, fy - ctr.1);
                fx = ctr.0 + d.0 * co - d.1 * s;
                fy = ctr.1 + d.0 * s + d.1 * co;
            }
            let tx = (fx - wx) / ww;
            let ty = (fy - wy) / wh;
            if !(0.0..1.0).contains(&tx) || !(0.0..1.0).contains(&ty) {
                continue;
            }
            // nearest sample, atlas px space
            let au = ((u0 + tx * (u1 - u0)) as usize).min(atlas_gen::ATLAS_W as usize - 1);
            let av = ((v0 + ty * (v1 - v0)) as usize).min(atlas_gen::ATLAS_H as usize - 1);
            let t = &ATLAS[(av * atlas_gen::ATLAS_W as usize + au) * 4..][..4];
            let mut col = [
                t[0] as f32 / 255.0,
                t[1] as f32 / 255.0,
                t[2] as f32 / 255.0,
                t[3] as f32 / 255.0,
            ];
            // tint multiply (shader does it pre-palette for pal>0, and as the
            // final multiply otherwise — same product either way)
            for i in 0..4 {
                col[i] *= tint[i];
            }
            if c.pal >= 1 {
                palette(&mut col);
            }
            if col[3] <= 0.0 {
                continue;
            }
            blend(fb, py * v.w + px, col);
        }
    }
}

fn step(edge: f32, v: f32) -> f32 {
    if v >= edge { 1.0 } else { 0.0 }
}

// GM shader 0 (shaderTemplate, "DOWNWELL"): threshold r/b/a, classify by
// channel, remap to the 4-color palette. Same math as shader.wgsl fs_main.
fn palette(c: &mut [f32; 4]) {
    c[0] = step(0.5, c[0]);
    c[2] = step(0.5, c[2]);
    c[3] = step(0.5, c[3]);
    const L: [f32; 3] = [250.0 / 256.0, 250.0 / 256.0, 250.0 / 256.0];
    const M: [f32; 3] = [250.0 / 256.0, 0.0, 0.0];
    const D: [f32; 3] = [5.0 / 256.0, 5.0 / 256.0, 5.0 / 256.0];
    const S: [f32; 3] = [0.0, 126.0 / 256.0, 250.0 / 256.0];
    let white = step(0.8, c[1]);
    let blue = step(0.8, c[2]) - white;
    let red = step(0.5, c[0] - c[1]);
    let black = step(0.5, 1.0 - c[0] - c[1] - c[2]);
    for (sel, pal) in [(black, D), (red, M), (blue, S), (white, L)] {
        if step(0.5, sel) == 1.0 {
            c[0] = pal[0];
            c[1] = pal[1];
            c[2] = pal[2];
        }
    }
}

// straight-alpha over (wgpu ALPHA_BLENDING)
fn blend(fb: &mut [u8], idx: usize, src: [f32; 4]) {
    let d = &mut fb[idx * 4..][..4];
    let sa = src[3];
    for i in 0..3 {
        let dst = d[i] as f32 / 255.0;
        d[i] = ((src[i] * sa + dst * (1.0 - sa)) * 255.0 + 0.5) as u8;
    }
    let da = d[3] as f32 / 255.0;
    d[3] = ((sa + da * (1.0 - sa)) * 255.0 + 0.5) as u8;
}
