// downwell_rs shared wgpu renderer: DrawList -> instanced quads -> the
// DOWNWELL palette shader, onto a surface (browser canvas today; app/'s
// capture target when it migrates). Palette slots, target size, and the
// pal=2 clip window are uniforms — the things the frontends vary.
//
// atlas_gen.rs is generated by tools/pack_assets.py into app/src; reference
// it in place (never copy) so a regenerated atlas reaches every frontend.
#[path = "../../app/src/atlas_gen.rs"]
pub mod atlas_gen;

#[cfg(not(target_arch = "wasm32"))]
pub static ATLAS: &[u8] = include_bytes!("../../assets/atlas.rgba");

#[repr(C)]
#[derive(Clone, Copy)]
struct Inst {
    rect: [f32; 4],
    uv: [f32; 4],
    color: [f32; 4],
    extra: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Uni {
    size: [f32; 4], // xy = target px, zw = pal2 clip x range
    pal: [[f32; 4]; 4],
}

pub struct Renderer {
    device: wgpu::Device,
    queue: wgpu::Queue,
    surface: wgpu::Surface<'static>,
    pipeline: wgpu::RenderPipeline,
    bind_group: wgpu::BindGroup,
    inst_buf: wgpu::Buffer,
    uni_buf: wgpu::Buffer,
    uni: Uni,
    insts: Vec<Inst>,
    pub clear: [f64; 3],
}

// GUI-space DrawList -> target-px instances. scale/off_x mirror the classic
// window mapping (cinema uses 1.0 / 0.0).
fn build_insts(cmds: &[sim::DrawCmd], scale: f32, off_x: f32, out: &mut Vec<Inst>) {
    out.clear();
    for c in cmds {
        let (rx, ry, rw, rh) = atlas_gen::sprite_rect(c.sprite, c.frame);
        let flip = c.w < 0.0;
        let (gx, gw) = if flip { (c.x + c.w, -c.w) } else { (c.x, c.w) };
        let (u0, u1) = if flip {
            ((rx + rw) as f32, rx as f32)
        } else {
            (rx as f32, (rx + rw) as f32)
        };
        let flipv = c.h < 0.0;
        let (gy, gh) = if flipv { (c.y + c.h, -c.h) } else { (c.y, c.h) };
        let (v0, v1) = if flipv {
            ((ry + rh) as f32, ry as f32)
        } else {
            (ry as f32, (ry + rh) as f32)
        };
        out.push(Inst {
            rect: [gx * scale + off_x, gy * scale, gw * scale, gh * scale],
            uv: [
                u0 / atlas_gen::ATLAS_W as f32,
                v0 / atlas_gen::ATLAS_H as f32,
                u1 / atlas_gen::ATLAS_W as f32,
                v1 / atlas_gen::ATLAS_H as f32,
            ],
            color: [
                ((c.color >> 24) & 0xFF) as f32 / 255.0,
                ((c.color >> 16) & 0xFF) as f32 / 255.0,
                ((c.color >> 8) & 0xFF) as f32 / 255.0,
                (c.color & 0xFF) as f32 / 255.0,
            ],
            extra: [c.pal as f32, c.rot.to_radians(), 0.0, 0.0],
        });
    }
}

impl Renderer {
    /// Browser-canvas renderer. `w`/`h` are the framebuffer (physical) size;
    /// clip is the pal=2 window in target px.
    #[cfg(target_arch = "wasm32")]
    pub async fn for_canvas(
        canvas: web_sys::HtmlCanvasElement,
        atlas: web_sys::ImageBitmap,
        w: u32,
        h: u32,
        clip: (f32, f32),
    ) -> Result<Renderer, String> {
        canvas.set_width(w);
        canvas.set_height(h);
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            // wgpu 22's WebGPU binding sends the removed
            // maxInterStageShaderComponents limit to current Chrome. Use its
            // WebGL2 GPU backend until the renderer crate is upgraded.
            backends: wgpu::Backends::GL,
            ..Default::default()
        });
        let surface = instance
            .create_surface(wgpu::SurfaceTarget::Canvas(canvas))
            .map_err(|e| format!("create_surface: {e}"))?;
        Renderer::new(instance, surface, atlas, w, h, clip).await
    }

    #[cfg(target_arch = "wasm32")]
    async fn new(
        instance: wgpu::Instance,
        surface: wgpu::Surface<'static>,
        atlas_bitmap: web_sys::ImageBitmap,
        w: u32,
        h: u32,
        clip: (f32, f32),
    ) -> Result<Renderer, String> {
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::LowPower, // a menu diorama: no need to spin the dGPU
                compatible_surface: Some(&surface),
                force_fallback_adapter: false,
            })
            .await
            .ok_or("no adapter")?;
        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    // stay within WebGL2 limits so the GL fallback works
                    required_limits: wgpu::Limits::downlevel_webgl2_defaults()
                        .using_resolution(adapter.limits()),
                    ..Default::default()
                },
                None,
            )
            .await
            .map_err(|e| format!("request_device: {e}"))?;

        let caps = surface.get_capabilities(&adapter);
        // non-srgb: colors are authored in the space the GM shader works in;
        // an sRGB target would gamma-encode them a second time
        let format = caps
            .formats
            .iter()
            .copied()
            .find(|f| !f.is_srgb())
            .unwrap_or(caps.formats[0]);
        surface.configure(
            &device,
            &wgpu::SurfaceConfiguration {
                usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
                format,
                width: w,
                height: h,
                present_mode: wgpu::PresentMode::Fifo,
                desired_maximum_frame_latency: 2,
                alpha_mode: caps.alpha_modes[0],
                view_formats: vec![],
            },
        );

        // atlas
        let atlas_size = wgpu::Extent3d {
            width: atlas_gen::ATLAS_W,
            height: atlas_gen::ATLAS_H,
            depth_or_array_layers: 1,
        };
        let atlas = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("atlas"),
            size: atlas_size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba8Unorm,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
            view_formats: &[],
        });
        queue.copy_external_image_to_texture(
            &wgpu::ImageCopyExternalImage {
                source: wgpu::ExternalImageSource::ImageBitmap(atlas_bitmap),
                origin: wgpu::Origin2d::ZERO,
                flip_y: false,
            },
            wgpu::ImageCopyTextureTagged {
                texture: &atlas,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
                color_space: wgpu::PredefinedColorSpace::Srgb,
                premultiplied_alpha: false,
            },
            atlas_size,
        );

        let uni = Uni {
            size: [w as f32, h as f32, clip.0, clip.1],
            // DOWNWELL defaults; set_palette overrides
            pal: [
                [250.0 / 256.0, 250.0 / 256.0, 250.0 / 256.0, 1.0],
                [250.0 / 256.0, 0.0, 0.0, 1.0],
                [5.0 / 256.0, 5.0 / 256.0, 5.0 / 256.0, 1.0],
                [0.0, 126.0 / 256.0, 250.0 / 256.0, 1.0],
            ],
        };
        let uni_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("uni"),
            size: core::mem::size_of::<Uni>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let shader = device.create_shader_module(wgpu::include_wgsl!("shader.wgsl"));
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            mag_filter: wgpu::FilterMode::Nearest,
            min_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: None,
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &bgl,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(
                        &atlas.create_view(&wgpu::TextureViewDescriptor::default()),
                    ),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(&sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: uni_buf.as_entire_binding(),
                },
            ],
        });
        let layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: None,
            bind_group_layouts: &[&bgl],
            push_constant_ranges: &[],
        });
        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: None,
            layout: Some(&layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: "vs_main",
                compilation_options: Default::default(),
                buffers: &[wgpu::VertexBufferLayout {
                    array_stride: core::mem::size_of::<Inst>() as u64,
                    step_mode: wgpu::VertexStepMode::Instance,
                    attributes: &wgpu::vertex_attr_array![0 => Float32x4, 1 => Float32x4, 2 => Float32x4, 3 => Float32x4],
                }],
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: "fs_main",
                compilation_options: Default::default(),
                targets: &[Some(wgpu::ColorTargetState {
                    format,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState::default(),
            depth_stencil: None,
            multisample: wgpu::MultisampleState::default(),
            multiview: None,
            cache: None,
        });

        // Cinema's full-frame dissolve alone is 3,360 tiles. Leave room for
        // composition growth without coupling this crate to sim::MAX_DRAW.
        let inst_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("instances"),
            size: (8192 * core::mem::size_of::<Inst>()) as u64,
            usage: wgpu::BufferUsages::VERTEX | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let mut r = Renderer {
            device,
            queue,
            surface,
            pipeline,
            bind_group,
            inst_buf,
            uni_buf,
            uni,
            insts: Vec::with_capacity(8192),
            clear: [0.0, 0.0, 0.0],
        };
        r.flush_uniforms();
        Ok(r)
    }

    fn flush_uniforms(&mut self) {
        let bytes = unsafe {
            core::slice::from_raw_parts(
                (&self.uni as *const Uni) as *const u8,
                core::mem::size_of::<Uni>(),
            )
        };
        self.queue.write_buffer(&self.uni_buf, 0, bytes);
    }

    /// Palette slots (l, m, d, s) as 0..1 rgb. Also sets the clear colour to
    /// the dark slot (the frame background in the cinema composition).
    pub fn set_palette(&mut self, pal: [[f32; 3]; 4]) {
        for (dst, src) in self.uni.pal.iter_mut().zip(pal.iter()) {
            *dst = [src[0], src[1], src[2], 1.0];
        }
        // clear through the same non-linear path the shader's colours take
        self.clear = [pal[2][0] as f64, pal[2][1] as f64, pal[2][2] as f64];
        self.flush_uniforms();
    }

    /// Render one composed DrawList (GUI units) and present.
    pub fn render(&mut self, cmds: &[sim::DrawCmd], scale: f32, off_x: f32) -> Result<(), String> {
        if cmds.len() > 8192 {
            return Err(format!("too many draw commands: {}", cmds.len()));
        }
        build_insts(cmds, scale, off_x, &mut self.insts);
        let n = self.insts.len();
        if n > 0 {
            let bytes = unsafe {
                core::slice::from_raw_parts(
                    self.insts.as_ptr() as *const u8,
                    n * core::mem::size_of::<Inst>(),
                )
            };
            self.queue.write_buffer(&self.inst_buf, 0, bytes);
        }
        let frame = self
            .surface
            .get_current_texture()
            .map_err(|e| format!("get_current_texture: {e}"))?;
        let view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());
        let mut enc = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor::default());
        {
            let mut rp = enc.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: None,
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: self.clear[0],
                            g: self.clear[1],
                            b: self.clear[2],
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
            });
            rp.set_pipeline(&self.pipeline);
            rp.set_bind_group(0, &self.bind_group, &[]);
            rp.set_vertex_buffer(0, self.inst_buf.slice(..));
            if n > 0 {
                rp.draw(0..6, 0..n as u32);
            }
        }
        self.queue.submit([enc.finish()]);
        frame.present();
        Ok(())
    }
}
