event_inherited();
bulPropertyCheck();
x = round(x);
y = round(y);
xsp = 0;
ysp = 0;
hitWallFx = 96;
original = 1;
trailRate = 0.25;
allSet = 0;
xxx = x + irandom_range(-2, 2);
inPlace = 0;
downward = 0;
laserWidth = 2;
xleft = x - laserWidth;
xright = x + laserWidth;
laserDist = 240;
ytop = y;
ybottom = y;
wallMet = 0;
