function script102_new()
{
    scrStartPat3();
    scrEndPat3();
    scrLeftPat3();
    scrRightPat3();
    scrShopPat3();
    i = 0;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.---..BBB\r\n\t......BB1\r\n\tB....BBB1\r\n\tB.d....B1\r\n\tBBBBBB.B1\r\n\t11BBBBBB1\r\n\t11B...BBB\r\n\t1B......B\r\n\tBB...b..B\r\n\tB.......B\r\n\t";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t..b......\r\n\t......BBB\r\n\t......BBB\r\n\tBB..d.BBB\r\n\tBB.BB1111\r\n\tBBBBB1111\r\n\tB.....BBB\r\n\t.......BB\r\n\t...---...\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t....BB...\r\n\t...BBB...\r\n\tB........\r\n\tBB.....d.\r\n\t1B.---.BB\r\n\t1B.....BB\r\n\t1BB.BB.BB\r\n\tBBBBBBBBB\r\n\t........B\r\n\t.........\r\n\t.--......";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tB........\r\n\tB......d.\r\n\tBBBBBB...\r\n\tBB...BBBB\r\n\tB...BBBBB\r\n\tBBBBBBBBB\r\n\t...1111BB\r\n\tBB.1111BB\r\n\tBB....BBB\r\n\t.......BB\r\n\t....--...\r\n\t";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t...b...BB\r\n\tB..--..BB\r\n\tBB.....BB\r\n\tBBBB....B\r\n\t111B....B\r\n\tBBBBBBBBB\r\n\tBB......B\r\n\tB....--.B\r\n\t.........\r\n\t";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t....B....\r\n\tBBBBB....\r\n\t...BBBBBB\r\n\tB.-....11\r\n\tB......11\r\n\tB...--...\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t......-..\r\n\t--.......\r\n\t..BBBBSGG\r\n\t..BBBB...\r\n\tBBBBBB..B\r\n\t....B...B\r\n\t....BBBBB\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t--.....BB\r\n\t......BBB\r\n\tBBGGSGBBB\r\n\tBBB...BBB\r\n\tBBB.-....\r\n\tBBB......\r\n\t......--.";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t11.......\r\n\t11......1\r\n\t1GGGGSGG1\r\n\t11.....11\r\n\t1......11\r\n\t1........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t1........\r\n\t1........\r\n\tGGSGGGGG1\r\n\t11.....11\r\n\t1......1.\r\n\t1........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.......11\r\n\t11....11.\r\n\t11GG..111\r\n\t11.GSGGG1\r\n\t11.....11\r\n\t1......11\r\n\t1........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t........B\r\n\t.......BB\r\n\t......BBB\r\n\tGSGGG.BBB\r\n\t....GGGBB\r\n\t.......BB\r\n\t........B\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.........\r\n\tGG11.11GG\r\n\t.GGGSGGG.\r\n\t..11111..\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t........1\r\n\t111....11\r\n\t..1GSG111\r\n\t111G1G11.\r\n\t111G1G11.\r\n\t111G1G11.\r\n\t.1.GGG111\r\n\t11.......\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t..BBBBBBB\r\n\tBBB......\r\n\t.........\r\n\t.......BB\r\n\t..GGGSGGB\r\n\t.GG....GB\r\n\tGG....BGG\r\n\t......BBB\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.....BBBB\r\n\t....BB...\r\n\t....B....\r\n\t....B....\r\n\tGGSGB....\r\n\t....BBBBB\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tGGGGG....\r\n\t1111GG...\r\n\t11111GGSG\r\n\t11111...G\r\n\t......GGG\r\n\tGGGGGGG..\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t...S...S.\r\n\t...GB..GB\r\n\tBBBGBS.GB\r\n\tBSBGBGBBB\r\n\t.G.G.GBBB\r\n\t.G...G...\r\n\t.G.......";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........";
    partMain[100] = i;
    i = 0;
}
