function script113()
{
    extraColumn = 1;
    levelLength = 16;
    genCount = -10;
    rightRoomAmt = 2;
    rightRoomMade = 0;
    leftRoomAmt = 1;
    shopMade = 0;
    scrStartPat2();
    scrEndPat2();
    scrLeftPat2();
    scrRightPat2();
    scrShopPat2();
    i = 0;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.........\r\n\tJ.....MMM\r\n\t.....J111\r\n\t......111\r\n\t%.e.....1\r\n\t---.....1\r\n\t.C......1\r\n\t........1\r\n\t.....e..1\r\n\t....MMMM1\r\n\t....11111\r\n\t.........\r\n\t.........\r\n\tMMM......\r\n\t111......\r\n\t.........\r\n\t";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t........e\r\n\tM.......-\r\n\t1BB.%....\r\n\t1MMMMM...\r\n\t111111...\r\n\t111111c.J\r\n\t111111...\r\n\tc.......c\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t%.....e..\r\n\tM.....MMM\r\n\t1....J.11\r\n\t1.......1\r\n\t1c.......\r\n\t1.....e..\r\n\t1J....MMM\r\n\t1.....111\r\n\t.........\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tJ...%....\r\n\t-.....MMM\r\n\t..e...111\r\n\t..-..J...\r\n\t..c..-...\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t..%......\r\n\tB.......J\r\n\tB....e...\r\n\tMM...--..\r\n\t11......B\r\n\t1...%.BBB\r\n\t....MMMMM\r\n\t....11111\r\n\t.....c...\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tc........\r\n\tM.......J\r\n\t1B.....e.\r\n\t1BB.%..--\r\n\t1MMMBB...\r\n\t1111MM...\r\n\t..1111...\r\n\t....c....\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t........c\r\n\tc........\r\n\t.e......1\r\n\tMM.....31\r\n\t1....%.B1\r\n\t1...MMMM1\r\n\t1...11111\r\n\t1...c.1.1\r\n\t1J......1\r\n\t........1\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t....MM...\r\n\t....11...\r\n\t.........\r\n\t1J.....J1\r\n\t........1\r\n\t........c\r\n\t-.%..%%.B\r\n\tc......BB\r\n\t.....MMMM\r\n\t.....1111\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t..%.%....\r\n\tc.......J\r\n\tBB.e...--\r\n\tMMMM.....\r\n\t1111....c\r\n\t11..--...\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t";
    i += 1;
    partMain[i] = "\r\n\t1........\r\n\t1J...%..M\r\n\t1....MM.1\r\n\t1%....111\r\n\t1-......1\r\n\t1......c1\r\n\t...MM....\r\n\t...11....\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t%%....c..\r\n\t--....MMM\r\n\t........1\r\n\t.........\r\n\t...e.e...\r\n\t...MMM...\r\n\t...111...\r\n\t.........\r\n\t.c.......\r\n\tMM......J\r\n\t111......\r\n\t.........\r\n\t.........\r\n\t.........\r\n\t.....e...\r\n\t.....--.";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tc.......1\r\n\t.%......1\r\n\tMM.....MM\r\n\t11J....11\r\n\t1......11\r\n\t1.....c.1\r\n\t1.%...MMM\r\n\t1--...111\r\n\t1........\r\n\t.........\r\n\t.........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t...e.....\r\n\t1MMM.....\r\n\t111.....J\r\n\t11.......\r\n\t1....e..-\r\n\t.....MM..\r\n\tJ.%......\r\n\t.---.....\r\n\t...c.....\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t........1\r\n\t.%.....J1\r\n\tMM......1\r\n\t1.......1\r\n\t.....e.11\r\n\t.....MMMM\r\n\t.....1111\r\n\tJ........\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tMM.......\r\n\t1.....c..\r\n\t......MMM\r\n\t..%..B..1\r\n\tMMMBBB..J\r\n\t111......";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t.c.......\r\n\tMMMM.....\r\n\t1111....1\r\n\t1111....1\r\n\t11.....%.\r\n\t1.....-MM\r\n\t.........\r\n\t";
    i += 1;
    partMain[i] = "\r\n\tJ........\r\n\t..%...%.J\r\n\t1........\r\n\t113333331\r\n\t1..333311\r\n\t11BBBB.11\r\n\t111BBB111\r\n\t....c....\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\tMM.......\r\n\t11......J\r\n\t11.....e.\r\n\t.......MM\r\n\t.......11\r\n\t.........";
    i += 1;
    partMain[i] = "\r\n\t.........\r\n\t......e..\r\n\t.BBBBBMMM\r\n\tBBB....11\r\n\t.........\r\n\t.........";
    partMain[100] = i;
    i = 0;
}
