function soundInitialize()
{
    initSfxFs();
    initSfxJl();
    initSfxBhit();
    global.emitterGunshot = audio_emitter_create();
    global.OLchannel[0] = 0;
    global.OLchannel[1] = 0;
    global.OLchannel[2] = 0;
    global.OLchannel[3] = 0;
    global.OLchannel[4] = 0;
    global.OLchannel[5] = 0;
    global.OLchannel[6] = 0;
    global.OLchannel[7] = 0;
    global.OLchannel[8] = 0;
    global.OLchannel[9] = 0;
    global.OLchannel[10] = 0;
    global.OLgain[0] = 1;
    global.OLgain[1] = 1;
    global.OLgain[2] = 1;
    global.OLgain[3] = 1;
    global.OLgain[4] = 1;
    global.OLgain[5] = 1;
    global.OLgain[6] = 1;
    global.OLgain[7] = 1;
    global.OLgain[8] = 1;
    global.OLgain[9] = 1;
    global.OLgain[10] = 1;
    OLorigGain[0] = 1;
    OLorigGain[1] = 1;
    OLorigGain[2] = 1;
    OLorigGain[3] = 1;
    OLorigGain[4] = 1;
    OLorigGain[5] = 1;
    OLorigGain[6] = 1;
    OLorigGain[7] = 1;
    OLorigGain[8] = 1;
    OLorigGain[9] = 1;
    OLorigGain[10] = 1;
    global.OLduckDur[0] = 0;
    global.OLduckDur[1] = 0;
    global.OLduckDur[2] = 0;
    global.OLduckDur[3] = 0;
    global.OLduckDur[4] = 0;
    global.OLduckDur[5] = 0;
    global.OLduckDur[6] = 0;
    global.OLduckDur[7] = 0;
    global.OLduckDur[8] = 0;
    global.OLduckDur[9] = 0;
    global.OLduckDur[10] = 0;
}
